apiVersion: v1
kind: Service
metadata:
  name: mysql-service-steve # Change This 
  namespace: trainingdev
spec:
  selector:
    app: mysql-steve # Change This 
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service-steve # Change This 
  namespace: trainingdev
spec:
  selector:
    app: wordpress-steve # Change This 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  name: wordpress-route-steve # Change This 
  namespace: trainingdev
spec:
  to:
    kind: Service
    name: wordpress-service-steve # Change This 
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
